"""AUTO-GENERATED by generator.py — do not edit by hand."""
import json

from brasilapi_mcp.client import ApiClient

_client = ApiClient()

# ---- Cep ----
async def get_cep(cep: str) -> str:
    """Busca endereço a partir de um CEP (v1).
    
    Args:
        cep: CEP com 8 dígitos, apenas números (ex: 01310100)."""
    result = await _client.get(f"/cep/v1/{cep}")
    return json.dumps(result, ensure_ascii=False, default=str)

async def get_cep_v2(cep: str) -> str:
    """Busca endereço a partir de um CEP (v2, inclui coordenadas quando disponível).
    
    Args:
        cep: CEP com 8 dígitos, apenas números."""
    result = await _client.get(f"/cep/v2/{cep}")
    return json.dumps(result, ensure_ascii=False, default=str)

# ---- Cnpj ----
async def get_cnpj(cnpj: str) -> str:
    """Dados cadastrais de uma empresa pelo CNPJ (Receita Federal).
    
    Args:
        cnpj: CNPJ com 14 dígitos, apenas números."""
    result = await _client.get(f"/cnpj/v1/{cnpj}")
    return json.dumps(result, ensure_ascii=False, default=str)

# ---- Bank ----
async def list_bank() -> str:
    """Lista todos os bancos do Brasil (código, nome, ISPB)."""
    result = await _client.get(f"/banks/v1")
    return json.dumps(result, ensure_ascii=False, default=str)

async def get_bank(code: str) -> str:
    """Detalhes de um banco pelo código de compensação.
    
    Args:
        code: Código de compensação do banco (ex: 341 = Itaú)."""
    result = await _client.get(f"/banks/v1/{code}")
    return json.dumps(result, ensure_ascii=False, default=str)

# ---- Ddd ----
async def get_ddd(ddd: str) -> str:
    """Estado e lista de cidades atendidas por um DDD.
    
    Args:
        ddd: Código DDD de 2 dígitos (ex: 71 = Bahia)."""
    result = await _client.get(f"/ddd/v1/{ddd}")
    return json.dumps(result, ensure_ascii=False, default=str)

# ---- Feriado ----
async def list_feriado(ano: str) -> str:
    """Feriados nacionais de um ano (fixos + móveis).
    
    Args:
        ano: Ano com 4 dígitos entre 1900 e 2199 (ex: 2026)."""
    result = await _client.get(f"/feriados/v1/{ano}")
    return json.dumps(result, ensure_ascii=False, default=str)

# ---- Isbn ----
async def get_isbn(isbn: str) -> str:
    """Informações de um livro pelo ISBN.
    
    Args:
        isbn: ISBN 10 ou 13, com ou sem hífens."""
    result = await _client.get(f"/isbn/v1/{isbn}")
    return json.dumps(result, ensure_ascii=False, default=str)

# ---- Taxa ----
async def list_taxa() -> str:
    """Lista taxas de juros e índices oficiais (Selic, CDI, IPCA...)."""
    result = await _client.get(f"/taxas/v1")
    return json.dumps(result, ensure_ascii=False, default=str)

async def get_taxa(sigla: str) -> str:
    """Valor de uma taxa/índice específico pela sigla.
    
    Args:
        sigla: Sigla da taxa (ex: Selic, CDI, IPCA)."""
    result = await _client.get(f"/taxas/v1/{sigla}")
    return json.dumps(result, ensure_ascii=False, default=str)

# ---- Ncm ----
async def list_ncm(search: str | None = None) -> str:
    """Lista/busca códigos NCM. Use o parâmetro 'search' para filtrar.
    
    Args:
        search: Termo de busca por descrição ou código NCM (opcional). (opcional)"""
    params = {"search": search}
    result = await _client.get(f"/ncm/v1", params=params)
    return json.dumps(result, ensure_ascii=False, default=str)

async def get_ncm(code: str) -> str:
    """Detalhes de um código NCM específico.
    
    Args:
        code: Código NCM (ex: 33030010)."""
    result = await _client.get(f"/ncm/v1/{code}")
    return json.dumps(result, ensure_ascii=False, default=str)

# ---- Pix ----
async def list_pix_participant() -> str:
    """Lista os participantes do arranjo PIX."""
    result = await _client.get(f"/pix/v1/participants")
    return json.dumps(result, ensure_ascii=False, default=str)

# ---- IbgeUf ----
async def list_ibge_uf() -> str:
    """Lista todas as Unidades da Federação (UFs) do IBGE."""
    result = await _client.get(f"/ibge/uf/v1")
    return json.dumps(result, ensure_ascii=False, default=str)

async def get_ibge_uf(code: str) -> str:
    """Detalhes de uma UF pelo código ou sigla.
    
    Args:
        code: Código IBGE ou sigla da UF (ex: 35 ou SP)."""
    result = await _client.get(f"/ibge/uf/v1/{code}")
    return json.dumps(result, ensure_ascii=False, default=str)

# ---- Corretora ----
async def list_corretora() -> str:
    """Lista as corretoras ativas registradas na CVM."""
    result = await _client.get(f"/cvm/corretoras/v1")
    return json.dumps(result, ensure_ascii=False, default=str)

# ---- RegistroBr ----
async def get_registro_br(domain: str) -> str:
    """Status de registro de um domínio .br no Registro.br.
    
    Args:
        domain: Domínio a consultar (ex: brasilapi.com.br)."""
    result = await _client.get(f"/registrobr/v1/{domain}")
    return json.dumps(result, ensure_ascii=False, default=str)

ALL_TOOLS = [
    get_cep,
    get_cep_v2,
    get_cnpj,
    list_bank,
    get_bank,
    get_ddd,
    list_feriado,
    get_isbn,
    list_taxa,
    get_taxa,
    list_ncm,
    get_ncm,
    list_pix_participant,
    list_ibge_uf,
    get_ibge_uf,
    list_corretora,
    get_registro_br,
]
