"""Spec-driven generator: reads specs/brasilapi_spec.json and emits tools/generated.py.

One spec entry -> one async tool function. The generator is written once and is
indifferent to spec size — add a group to the JSON and the tool appears on the
next run. Run: python -m brasilapi_mcp.generator
"""

import json
import keyword
import re
from pathlib import Path

SPEC_PATH = Path(__file__).resolve().parents[2] / "specs" / "brasilapi_spec.json"
OUT_PATH = Path(__file__).resolve().parent / "tools" / "generated.py"

_PATH_PARAM_RE = re.compile(r"\{([^}]+)\}")


def _safe(name: str) -> str:
    """Append '_' to Python reserved words so signatures stay valid."""
    return f"{name}_" if keyword.iskeyword(name) else name


def _render_endpoint(ep: dict) -> str:
    func = ep["func"]
    method = ep["method"].lower()
    path = ep["path"]
    summary = ep.get("summary", "").strip()
    path_params = ep.get("path_params", [])
    query_params = ep.get("query_params", [])

    # positional args = path params (required); keyword args = query params (optional)
    args = [f"{_safe(p['name'])}: str" for p in path_params]
    args += [f"{_safe(q['name'])}: str | None = None" for q in query_params]
    sig = ", ".join(args)

    # build the runtime path by substituting {param} with the safe local var
    path_expr = path
    for p in path_params:
        path_expr = path_expr.replace("{" + p["name"] + "}", "{" + _safe(p["name"]) + "}")

    query_lines = ""
    if query_params:
        pairs = ", ".join(f'"{q["name"]}": {_safe(q["name"])}' for q in query_params)
        query_lines = f"    params = {{{pairs}}}\n"
        call = f'await _client.{method}(f"{path_expr}", params=params)'
    else:
        call = f'await _client.{method}(f"{path_expr}")'

    # docstring
    doc = [summary or f"{method.upper()} {path}"]
    if path_params or query_params:
        doc.append("")
        doc.append("Args:")
        for p in path_params:
            doc.append(f"    {_safe(p['name'])}: {p.get('desc', '')}")
        for q in query_params:
            doc.append(f"    {_safe(q['name'])}: {q.get('desc', '')} (opcional)")
    docstring = "\n    ".join(doc)

    return (
        f"async def {func}({sig}) -> str:\n"
        f'    """{docstring}"""\n'
        f"{query_lines}"
        f"    result = {call}\n"
        f"    return json.dumps(result, ensure_ascii=False, default=str)\n"
    )


def generate() -> int:
    spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    blocks = [
        '"""AUTO-GENERATED by generator.py — do not edit by hand."""',
        "import json",
        "",
        "from brasilapi_mcp.client import ApiClient",
        "",
        "_client = ApiClient()",
        "",
    ]
    count = 0
    for group in spec["groups"]:
        blocks.append(f"# ---- {group['name']} ----")
        for ep in group["endpoints"]:
            blocks.append(_render_endpoint(ep))
            count += 1

    names = [ep["func"] for g in spec["groups"] for ep in g["endpoints"]]
    blocks.append("ALL_TOOLS = [")
    for n in names:
        blocks.append(f"    {n},")
    blocks.append("]")
    blocks.append("")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(blocks), encoding="utf-8")
    return count


if __name__ == "__main__":
    n = generate()
    print(f"✓ geradas {n} tools em {OUT_PATH.relative_to(Path.cwd()) if OUT_PATH.is_relative_to(Path.cwd()) else OUT_PATH}")
